# Generated by Django 5.1.1 on 2024-11-29 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadeEntrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_entrevista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatos', models.ManyToManyField(related_name='entrevistas', to=settings.AUTH_USER_MODEL)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevista', to='entrevistas.disponibilidadeentrevista')),
            ],
        ),
    ]
