# Generated by Django 5.1.1 on 2024-12-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0002_mensagementrevista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensagemEntrevista',
        ),
    ]
