# Generated by Django 5.1.1 on 2024-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('membro', 'Membro'), ('candidato', 'Candidato')], default='candidato', max_length=10, verbose_name='Tipo de Usuário'),
        ),
    ]
