# Generated by Django 5.1.1 on 2024-11-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_aviso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
    ]
