# Generated by Django 5.1.1 on 2024-11-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_aviso_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={},
        ),
        migrations.AddField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='externo', max_length=10),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
