# Generated by Django 5.1.1 on 2024-11-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_aviso_options_aviso_tipo_alter_aviso_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status_aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10, verbose_name='Status de Aprovação'),
        ),
    ]
