# Generated by Django 5.1.1 on 2024-12-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_disponibilidade_dinamica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidade',
            name='membro',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_entrevista',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10, verbose_name='Status de Aprovação'),
        ),
        migrations.DeleteModel(
            name='Dinamica',
        ),
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
    ]
