# Generated by Django 5.1.1 on 2024-12-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_disponibilidade_membro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status_palestra',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10, verbose_name='Status Palestra'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status_aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10, verbose_name='Status Dinâmica'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status_entrevista',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10, verbose_name='Status Entrevista'),
        ),
    ]
