# Generated by Django 5.1.1 on 2024-12-01 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_status_palestra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='status_aprovacao',
            new_name='status_dinamica',
        ),
    ]
